import { truncateDescription } from '@/utils/constants';
import { PdfTemplateProps } from './types';

export const getPdfTemplate = ({ data, columns }: PdfTemplateProps): string => `
  <div style="color: #000;">
    <!-- Report Header -->
    <div style="text-align: center; color: #000;">
      <h2>Project Management Report</h2>
      <p style="text-align: center;">Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    
    <!-- Report Table -->
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
      <thead>
        <tr>
          ${columns
            .map(
              (column) =>
                `<th style="border: 1px solid #000; padding: 8px; text-align: left; background-color: #f2f2f2;">
                  ${column.title}
                </th>`
            )
            .join('')}
        </tr>
      </thead>
      <tbody>
        ${data
          .map(
            (row) => `
            <tr>
              ${columns
                .map(
                  (column) =>
                    `<td style="border: 1px solid #000; padding: 8px; text-align: left;">
                      ${
                        column.key === 'description'
                          ? truncateDescription(row[column.key])
                          : (row[column.key] ?? '-')
                      }
                    </td>`
                )
                .join('')}
            </tr>`
          )
          .join('')}
      </tbody>
    </table>
    
    <!-- Footer -->
    <footer style="margin-top: 20px; text-align: center; font-size: 12px; color: gray;">
      Report generated by <span style="color: blue;">NexTask</span>
    </footer>
  </div>
`;
