import { NextResponse } from 'next/server';
import { ObjectId } from 'mongodb';
import clientPromise from '../../../lib/mongodb';
import { DATABASE_NAME } from '../../../config';
import { verifySystemAdmin } from '../../../helpers';
import { validateSlug, normalizeSlug } from '../../../lib/organizations';
import { resolvePlanNameToId, resolvePlanSearchToIds } from '../../../lib/planResolver';
import bcrypt from 'bcrypt';

export async function POST(request: Request) {
  // 1. Verify JWT
  // 2. Ensure isSystemAdmin === true
  const { decoded, error, status } = await verifySystemAdmin(request);
  if (error) {
    return NextResponse.json({ error }, { status });
  }

  try {
    const body = await request.json();
    const {
      name,
      slug,
      owner,
      planName,
      planStartDate,
      planEndDate,
    } = body;

    // Validate input
    if (!name || !slug || !owner || !owner.firstName || !owner.lastName || !owner.email || !owner.password) {
      return NextResponse.json(
        { error: 'Name, slug, and owner (firstName, lastName, email, password) are required' },
        { status: 400 }
      );
    }

    // Validate name length
    if (name.length < 2 || name.length > 100) {
      return NextResponse.json(
        { error: 'Organization name must be between 2 and 100 characters' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(owner.email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // Validate password length
    if (owner.password.length < 6) {
      return NextResponse.json(
        { error: 'Password must be at least 6 characters' },
        { status: 400 }
      );
    }

    // Normalize and validate slug
    const normalizedSlug = normalizeSlug(slug);
    if (!validateSlug(normalizedSlug)) {
      return NextResponse.json(
        { error: 'Slug must contain only lowercase letters, numbers, and hyphens (max 50 characters)' },
        { status: 400 }
      );
    }

    const client = await clientPromise;
    const db = client.db(DATABASE_NAME);
    const organizationsCollection = db.collection('organizations');
    const usersCollection = db.collection('users');
    const plansCollection = db.collection('plans');

    // 3. Validate slug uniqueness
    const existingOrg = await organizationsCollection.findOne({
      slug: normalizedSlug,
      deletedAt: null,
    });
    if (existingOrg) {
      return NextResponse.json(
        { error: 'Organization with this slug already exists' },
        { status: 409 }
      );
    }

    // Check if owner email already exists
    const existingUser = await usersCollection.findOne({ email: owner.email });
    if (existingUser) {
      return NextResponse.json(
        { error: 'User with this email already exists' },
        { status: 400 }
      );
    }

    // Hash owner password
    const hashedPassword = await bcrypt.hash(owner.password, 10);

    // Get owner firstName and lastName from request
    const firstName = owner.firstName.trim();
    const lastName = owner.lastName.trim();

    // 4. Resolve plan from planName (if provided)
    // planId is the source of truth; planName is for display
    let resolvedPlanId: ObjectId | null = null;
    let resolvedPlanName = '';
    if (planName && typeof planName === 'string' && planName.trim() !== '') {
      const trimmedPlanName = planName.trim();
      const planDoc = await plansCollection.findOne({
        plan_name: { $regex: new RegExp(`^${trimmedPlanName}$`, 'i') },
        status: 'active',
        deletedAt: null,
      });
      if (!planDoc) {
        return NextResponse.json(
          { error: 'Plan not found or inactive for the provided planName' },
          { status: 400 }
        );
      }
      resolvedPlanId = planDoc._id;
      resolvedPlanName = planDoc.plan_name;
    }

    // 5. Create organization document
    // Note: _id will be auto-generated by MongoDB and serves as org_id
    const newOrganization = {
      name,
      slug: normalizedSlug,
      slug_history: [normalizedSlug],
      status: 'active',
      planId: resolvedPlanId || null,
      planName: resolvedPlanName,
      planStartDate: planStartDate ? new Date(planStartDate) : null,
      planEndDate: planEndDate ? new Date(planEndDate) : null,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
      // ownerId will be set after owner user is created
    };

    // Insert organization first to get the _id (org_id)
    const orgResult = await organizationsCollection.insertOne(newOrganization);
    const org_id = orgResult.insertedId;

    // 5. Create owner user
    const ownerUser = {
      firstName,
      lastName,
      email: owner.email,
      password: hashedPassword,
      role: 'ORG_ADMIN',
      org_id: org_id, // Set org_id to organization._id
      createdAt: new Date(),
      updatedAt: new Date(),
      emailVerified: false,
      isTemporaryPassword: false,
    };

    let ownerId: ObjectId;
    try {
      const ownerResult = await usersCollection.insertOne(ownerUser);
      ownerId = ownerResult.insertedId;
    } catch (userError: any) {
      // If owner creation fails, clean up the organization
      await organizationsCollection.deleteOne({ _id: org_id });
      console.error('Error creating owner user:', userError);
      return NextResponse.json(
        { error: 'Failed to create owner user' },
        { status: 500 }
      );
    }

    // 6. Update organization.ownerId
    try {
      await organizationsCollection.updateOne(
        { _id: org_id },
        { $set: { ownerId } }
      );
    } catch (updateError: any) {
      // If update fails, clean up both organization and owner
      await organizationsCollection.deleteOne({ _id: org_id });
      await usersCollection.deleteOne({ _id: ownerId });
      console.error('Error updating organization with ownerId:', updateError);
      return NextResponse.json(
        { error: 'Failed to update organization' },
        { status: 500 }
      );
    }

    // 7. Return created organization with owner information
    const createdOrg = await organizationsCollection.findOne({ _id: org_id });

    // Fetch owner information
    let ownerEmail = null;
    let ownerFirstName = null;
    let ownerLastName = null;
    if (ownerId) {
      const owner = await usersCollection.findOne({ _id: ownerId });
      if (owner) {
        ownerEmail = owner.email || null;
        ownerFirstName = owner.firstName || null;
        ownerLastName = owner.lastName || null;
      }
    }

    return NextResponse.json(
      {
        success: true,
        organization: {
          _id: createdOrg!._id.toString(),
          name: createdOrg!.name,
          slug: createdOrg!.slug,
          status: createdOrg!.status,
          planName: createdOrg!.planName || '',
          planId: createdOrg!.planId ? createdOrg!.planId.toString() : null,
          ownerId: createdOrg!.ownerId.toString(),
          ownerEmail,
          ownerFirstName,
          ownerLastName,
          createdAt: createdOrg!.createdAt,
        },
      },
      { status: 201 }
    );
  } catch (error: any) {
    console.error('Error creating organization:', error);

    // Handle duplicate key errors
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'Organization with this slug already exists' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to create organization' },
      { status: 500 }
    );
  }
}

export async function GET(request: Request) {
  // 1. Verify JWT
  // 2. Ensure isSystemAdmin === true
  const { decoded, error, status } = await verifySystemAdmin(request);
  if (error) {
    return NextResponse.json({ error }, { status });
  }

  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '10', 10);
    const search = searchParams.get('search') || '';
    const planSearch = searchParams.get('planSearch') || '';

    const client = await clientPromise;
    const db = client.db(DATABASE_NAME);
    const organizationsCollection = db.collection('organizations');
    const usersCollection = db.collection('users');
    const plansCollection = db.collection('plans');

    // Build query for non-deleted organizations
    const query: any = { deletedAt: null };

    // Global search: search across organization-related fields (excluding plan-based logic)
    if (search) {
      const searchConditions: any[] = [
        { name: { $regex: search, $options: 'i' } },
        { slug: { $regex: search, $options: 'i' } },
        { status: { $regex: search, $options: 'i' } },
      ];

      // Search by owner information - find matching users (email, firstName, lastName)
      const matchingOwners = await usersCollection
        .find({
          $or: [
            { email: { $regex: search, $options: 'i' } },
            { firstName: { $regex: search, $options: 'i' } },
            { lastName: { $regex: search, $options: 'i' } },
          ],
        })
        .project({ _id: 1 })
        .toArray();

      if (matchingOwners.length > 0) {
        const ownerIds = matchingOwners.map((owner) => owner._id);
        searchConditions.push({ ownerId: { $in: ownerIds } });
      }

      query.$or = searchConditions;
    }

    // Plan-based filtering via planSearch (planId-driven)
    if (planSearch) {
      const planIds = await resolvePlanSearchToIds(planSearch);
      if (planIds.length === 0) {
        // No matching plans => no organizations to return
        return NextResponse.json(
          {
            success: true,
            organizations: [],
            pagination: {
              page,
              limit,
              total: 0,
              totalPages: 0,
            },
          },
          { status: 200 }
        );
      }
      query.planId = { $in: planIds };
    }

    // Get total count for pagination
    const total = await organizationsCollection.countDocuments(query);

    // Calculate skip for pagination
    const skip = (page - 1) * limit;

    // Fetch organizations with pagination, excluding soft-deleted ones
    // Sort by createdAt descending
    const organizations = await organizationsCollection
      .find(query, {
        projection: {
          _id: 1,
          name: 1,
          slug: 1,
          status: 1,
          planId: 1,
          planName: 1,
          ownerId: 1,
          createdAt: 1,
        },
      })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .toArray();

    // Populate owner information
    const formattedOrganizations = await Promise.all(
      organizations.map(async (org) => {
        let ownerEmail = null;
        let ownerFirstName = null;
        let ownerLastName = null;
        if (org.ownerId) {
          const owner = await usersCollection.findOne({ _id: new ObjectId(org.ownerId) });
          if (owner) {
            ownerEmail = owner.email || null;
            ownerFirstName = owner.firstName || null;
            ownerLastName = owner.lastName || null;
          }
        }
        return {
          _id: org._id.toString(),
          name: org.name,
          slug: org.slug,
          status: org.status,
          planId: org.planId ? org.planId.toString() : null,
          planName: org.planName || '',
          ownerId: org.ownerId ? org.ownerId.toString() : null,
          ownerEmail,
          ownerFirstName,
          ownerLastName,
          createdAt: org.createdAt,
        };
      })
    );

    return NextResponse.json(
      {
        success: true,
        organizations: formattedOrganizations,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit),
        },
      },
      { status: 200 }
    );
  } catch (error: any) {
    console.error('Error fetching organizations:', error);
    return NextResponse.json(
      { error: 'Failed to fetch organizations' },
      { status: 500 }
    );
  }
}


